version: '3'

services:
  frontend:
    build:
      context: .
    volumes:
      - react_build:/react/dist
  nginx:
    image: nginx:latest
    ports:
      - "80:8090"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - frontend
volumes:
  react_build:
